name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Run Build
        run: yarn build

      - uses: appleboy/scp-action@master
        with:
          host: 172.31.91.76
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "., !/node_modules"
          target: "test"
          
